use ASQ;

insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (1, UUID(), CURDATE(), 0, 0, 'Architect');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (2, UUID(), CURDATE(), 0, 0, 'Plumber');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (3, UUID(), CURDATE(), 0, 0, 'Electrician ');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (4, UUID(), CURDATE(), 0, 0, 'Carpenter');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (5, UUID(), CURDATE(), 0, 0, 'General Contractor');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (6, UUID(), CURDATE(), 0, 0, 'HMO');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (7, UUID(), CURDATE(), 0, 0, 'Buy-to-Let');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (8, UUID(), CURDATE(), 0, 0, 'Developer');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (9, UUID(), CURDATE(), 0, 0, 'Sourcer');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (10, UUID(), CURDATE(), 0, 0, 'Planning Consultant');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (11, UUID(), CURDATE(), 0, 0, 'Quantity Surveyor');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (12, UUID(), CURDATE(), 0, 0, 'Estate agent');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (13, UUID(), CURDATE(), 0, 0, 'Rental agent');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (14, UUID(), CURDATE(), 0, 0, 'Mentor');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (15, UUID(), CURDATE(), 0, 0, 'Engineer');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (16, UUID(), CURDATE(), 0, 0, 'Accountant');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (17, UUID(), CURDATE(), 0, 0, 'Mortgage Broker');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (18, UUID(), CURDATE(), 0, 0, 'Investor');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (19, UUID(), CURDATE(), 0, 0, 'Property Solicitor');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (20, UUID(), CURDATE(), 0, 0, 'Acoustic professional ');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (21, UUID(), CURDATE(), 0, 0, 'Rent-to-Rent');
insert into tb_Focus(Id, UniqueId, CreationDateUtc, CreationUserId, Inactive, Description) values (22, UUID(), CURDATE(), 0, 0, 'Other');